# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:###
# https://aka.ms/yaml#######
# include is what will cause a test to run. changes will take affect in saves after yml is saved
# Delay
# Delay further execution of a workflow by a fixed time
jobs:
- job: RunsOnServer
  pool: Server
  steps:
  - task: Delay@1
    inputs:
      delayForMinutes: '1'

trigger:
  branches:
    include:
      - main
      - master
    exclude:
      - branch
#- none#main 

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: srlTest@0
  name: LRC
  inputs:
    serverEndpoint: 'LRC MP User Account'
    tenantid: '111411822'
    projectid: '1'
    testid: '17'

# Delay
# Delay further execution of a workflow by a fixed time

- script: echo Run Id of the LRC run $(LRC.LRC_RUN_ID)
  displayName: 'Catch the run Id of the LRC run'

